
bot:
  BOT_TOKEN: <5060428209:AAG_mGRO57BgUnWjJFI6a5oCHVNIpkRnhnQ>
  BOT_USERNAME: <UA_DSNS_bot>
server:
  PORT: $PORT
spring:
  main:
    allow-circular-references: true
  # Database configuration
  datasource:
#    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.114.200.41:5432/dsns_bot
    username: postgres
    password: bgd
  jpa:
  # PotGIS configuration
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    open-in-view: false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect


